### ISSUE TITLE
path to file is not working for me 

### ISSUE THREAD

**Issue by rohitrepo1** [gscho/setup-cloud-custodian#6]
do we need to copy the policy.yml file inside the action machine? if yes how can we do that ? 

Run custodian run -s out /Project-xx/aws/dev/policy.yml

custodian run -s out ./Project-xx/aws/dev/policy.yml

shell: /usr/bin/bash -e {0}

custodian.commands:ERROR policy file does not exist (./Project-xx/aws/dev/policy.yml)

custodian.commands:ERROR Found 1 errors.  Exiting.

**Comment by gscho** [comment]
Check out this example:

https://github.com/vmware-tanzu/kubeapps/blob/main/.github/workflows/ci-custodian-rules.yaml

**Comment by rohitrepo1** [comment]
worked for me thank you!

Does the cloud custodian work with OIDC auth or do we have the provide creds?  I have established AWS git connectivity with oidc   (https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws.)

**Comment by gscho** [comment]
OIDC is how github authenticates with AWS. You still need to use the `aws-actions/configure-aws-credentials` action to setup credentials that work with cloud custodian or the awscli.

Closing because this is getting off topic for the scope of this action.
